# Generated by Django 2.2.6 on 2019-12-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20191206_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picure',
            new_name='profile_picture',
        ),
    ]
